export interface ProductDetails {
  ingredients: string;
  usage: string;
  benefits: string[];
  size: string;
  suitableFor: string;
}

const details: Record<string, ProductDetails> = {
  "Oli de Figa de Moro": { ingredients: "Oli de llavor de figa de moro, esqualà vegetal, vitamina E i extracte de romaní.", usage: "Aplicar 3 o 4 gotes a la nit sobre el rostre i el coll nets. Massatjar fins que s'absorbeixi.", benefits: ["Nodreix intensament", "Reforça la barrera cutània", "Suavitza les línies d'expressió"], size: "30 ml", suitableFor: "Tot tipus de pell, especialment seca o madura" },
  "Crema d'Alga Vermella": { ingredients: "Extracte d'alga vermella, àcid hialurònic, aigua marina i mantega de karité.", usage: "Aplicar al matí i a la nit després del sèrum, amb moviments ascendents.", benefits: ["Hidratació prolongada", "Calma la sensibilitat", "Millora l'elasticitat"], size: "50 ml", suitableFor: "Pell sensible, normal o deshidratada" },
  "Tònic de Neroli": { ingredients: "Hidrolat de flor de taronger, àloe vera, niacinamida i extracte de cogombre.", usage: "Vaporitzar sobre el rostre net o aplicar amb un disc de cotó. No aclarir.", benefits: ["Refresca i equilibra", "Prepara la pell", "Aporta lluminositat"], size: "100 ml", suitableFor: "Tot tipus de pell" },
  "Netejador d'Argila": { ingredients: "Argila blanca, argila volcànica, glicerina vegetal i oli d'oliva.", usage: "Massatjar sobre la pell humida durant un minut i retirar amb aigua tèbia.", benefits: ["Neteja en profunditat", "Purifica els porus", "Respecta la hidratació"], size: "120 ml", suitableFor: "Pell mixta, greixosa o congestionada" },
  "Sèrum Lluminositat": { ingredients: "Vitamina C estabilitzada, extracte de magrana, àcid ferúlic i àloe vera.", usage: "Aplicar 2 o 3 gotes al matí abans de la crema i del protector solar.", benefits: ["Uniformitza el to", "Aporta lluminositat", "Protecció antioxidant"], size: "30 ml", suitableFor: "Pell apagada o amb to irregular" },
  "Contorn d'Ulls": { ingredients: "Pèptids de seda, cafeïna, àcid hialurònic i extracte de blauet.", usage: "Aplicar una petita quantitat amb tocs suaus al voltant del contorn, al matí i a la nit.", benefits: ["Suavitza les línies", "Redueix les bosses", "Il·lumina la mirada"], size: "15 ml", suitableFor: "Tot tipus de pell" },
  "Mascareta de Nit": { ingredients: "Ceramides, oli d'ametlles, pantenol i extracte de lavanda.", usage: "Estendre una capa fina abans d'anar a dormir, dues o tres nits per setmana. Retirar al matí.", benefits: ["Repara durant la nit", "Nodreix profundament", "Recupera el confort"], size: "60 ml", suitableFor: "Pell seca, sensible o fatigada" },
  "Xampú de Romaní": { ingredients: "Extracte de romaní, cafeïna vegetal, àloe vera i tensioactius suaus.", usage: "Aplicar sobre el cabell mullat, massatjar el cuir cabellut i aclarir. Repetir si cal.", benefits: ["Neteja suaument", "Estimula el cuir cabellut", "Aporta vitalitat"], size: "250 ml", suitableFor: "Cabell normal, fi o debilitat" },
  "Condicionador de Karité": { ingredients: "Mantega de karité, oli de jojoba, proteïna de blat i pantenol.", usage: "Aplicar de mitjans a puntes després del xampú. Deixar actuar de 2 a 3 minuts i aclarir.", benefits: ["Desembolica", "Nodreix les puntes", "Redueix l'encrespament"], size: "250 ml", suitableFor: "Cabell sec, arrissat o danyat" },
  "Oli d'Argània": { ingredients: "Oli d'argània, esqualà vegetal i vitamina E.", usage: "Distribuir 1 o 2 gotes en mitjans i puntes, sobre cabell humit o sec.", benefits: ["Aporta brillantor", "Segella les puntes", "Suavitza sense apelmassar"], size: "50 ml", suitableFor: "Tot tipus de cabell" },
  "Bruma Capil·lar": { ingredients: "Aigua de flor de taronger, extracte de figa, pantenol i proteïna vegetal.", usage: "Vaporitzar a 20 cm sobre el cabell sec o humit. No necessita aclariment.", benefits: ["Perfuma delicadament", "Refresca el cabell", "Aporta suavitat"], size: "100 ml", suitableFor: "Tot tipus de cabell" },
  "Mascareta de Fang": { ingredients: "Argila rhassoul, minerals marins, oli d'oliva i sàlvia.", usage: "Aplicar sobre el cuir cabellut i les arrels humides. Deixar 10 minuts i aclarir abundantment.", benefits: ["Elimina residus", "Equilibra l'arrel", "Retorna lleugeresa"], size: "200 ml", suitableFor: "Cuir cabellut gras o amb acumulació" },
  "Sèrum Anticaiguda": { ingredients: "Cafeïna verda, pèptids vegetals, romaní i niacinamida.", usage: "Aplicar per seccions sobre el cuir cabellut net i massatjar. No aclarir. Ús diari.", benefits: ["Enforteix l'arrel", "Estimula el creixement", "Millora la densitat"], size: "50 ml", suitableFor: "Cabell fi o amb caiguda estacional" },
  "Exfoliant de Sal Marina": { ingredients: "Sal marina fina, oli de jojoba, menta i extracte de llimona.", usage: "Massatjar suaument sobre el cuir cabellut humit abans del xampú, un cop per setmana.", benefits: ["Desincrusta impureses", "Activa la microcirculació", "Purifica l'arrel"], size: "150 ml", suitableFor: "Tot tipus de cuir cabellut, excepte irritat" },
  "Bàlsam Relaxant": { ingredients: "Calèndula, lavanda, mantega de karité i bisabolol.", usage: "Aplicar sobre les zones sensibilitzades i massatjar fins que s'absorbeixi. Repetir quan calgui.", benefits: ["Calma la irritació", "Nodreix i protegeix", "Redueix la tibantor"], size: "75 ml", suitableFor: "Pell sensible, seca o irritada" },
  "Elixir de Sol": { ingredients: "Oli d'ametlles, mica mineral daurada, vitamina E i extracte de pastanaga.", usage: "Agitar i aplicar sobre espatlles, braços i cames. Evitar el contacte amb teixits clars.", benefits: ["Realça el bronzejat", "Aporta brillantor setinada", "Nodreix la pell"], size: "100 ml", suitableFor: "Tot tipus de pell" },
  "Crema de Mans": { ingredients: "Mantega de llimona, oli d'ametlles, glicerina i vitamina E.", usage: "Massatjar mans i cutícules tantes vegades com calgui.", benefits: ["Repara la sequedat", "Suavitza les cutícules", "Protegeix sense sensació greixosa"], size: "50 ml", suitableFor: "Mans seques o exposades" },
  "Esprai Mineral": { ingredients: "Aigua termal, magnesi, zinc i extracte de cogombre.", usage: "Polvoritzar sobre el rostre o el cos i deixar que s'absorbeixi. Es pot utilitzar durant tot el dia.", benefits: ["Refresca a l'instant", "Calma l'envermelliment", "Reposa minerals"], size: "100 ml", suitableFor: "Tot tipus de pell, fins i tot sensible" },
  "Gel d'Àloe Pur": { ingredients: "Àloe vera ecològic, pantenol, cogombre i al·lantoïna.", usage: "Aplicar generosament sobre la pell neta després del sol o quan necessiti calma.", benefits: ["Calma immediatament", "Hidrata sense greix", "Ajuda a reparar"], size: "150 ml", suitableFor: "Pell sensible o exposada al sol" },
  "Protector Urbà": { ingredients: "Filtres solars d'ampli espectre, niacinamida, vitamina E i te verd.", usage: "Aplicar com a últim pas cada matí. Renovar cada dues hores durant l'exposició.", benefits: ["Protecció SPF 50", "Defensa antioxidant", "Acabat invisible"], size: "50 ml", suitableFor: "Tot tipus de pell" },
  "Concentrat Reafirmant": { ingredients: "Pèptids tensors, àcid hialurònic, silici orgànic i centella asiàtica.", usage: "Aplicar mitja ampolla sobre rostre, coll i escot abans de la crema.", benefits: ["Efecte tensor", "Millora la fermesa", "Hidratació concentrada"], size: "7 × 2 ml", suitableFor: "Pell madura o amb pèrdua de fermesa" },
  "Mantega Mediterrània": { ingredients: "Mantega de karité, oli d'oliva, gessamí i vitamina E.", usage: "Massatjar sobre la pell neta, insistint en les zones més seques.", benefits: ["Nutrició intensa", "Suavitat duradora", "Perfum delicat"], size: "200 ml", suitableFor: "Pell normal a molt seca" },
  "Exfoliant d'Oliva": { ingredients: "Pinyol d'oliva micronitzat, oli d'oliva, mel i romaní.", usage: "Massatjar sobre la pell humida amb moviments circulars i aclarir. Utilitzar una o dues vegades per setmana.", benefits: ["Allisa la textura", "Retira cèl·lules mortes", "Prepara per a la hidratació"], size: "200 ml", suitableFor: "Tot tipus de pell corporal" },
  "Oli Reafirmant": { ingredients: "Oli de pinyol de raïm, heura, xiprer i centella asiàtica.", usage: "Massatjar diàriament amb moviments ascendents a cames, abdomen i braços.", benefits: ["Millora l'elasticitat", "Afavoreix el massatge drenant", "Nodreix la pell"], size: "100 ml", suitableFor: "Pell amb manca de fermesa" },
  "Gel de Bany Botànic": { ingredients: "Àloe vera, aigua de flor de taronger, glicerina vegetal i tensioactius suaus.", usage: "Aplicar sobre la pell humida, massatjar fins a formar escuma i aclarir.", benefits: ["Neteja respectuosa", "Manté el confort", "Aroma botànic"], size: "300 ml", suitableFor: "Tot tipus de pell, fins i tot sensible" },
  "Crema de Coll": { ingredients: "Pèptids, elastina vegetal, àcid hialurònic i oli de rosa mosqueta.", usage: "Aplicar al matí i a la nit des de l'escot cap a la mandíbula amb moviments ascendents.", benefits: ["Millora la fermesa", "Suavitza les arrugues", "Hidrata coll i escot"], size: "50 ml", suitableFor: "Pell madura o amb pèrdua d'elasticitat" },
  "Desodorant de Pedra": { ingredients: "Alum potàssic, aigua de sàlvia, àloe vera i glicerina.", usage: "Humitejar lleugerament i lliscar sobre la pell neta. Aclarir la pedra després d'utilitzar-la.", benefits: ["Control natural de l'olor", "Sense perfum intens", "No deixa residus"], size: "90 g", suitableFor: "Tot tipus de pell" },
  "Llet Corporal": { ingredients: "Aigua de roses, oli d'ametlles, àloe vera i vitamina E.", usage: "Aplicar diàriament sobre tot el cos amb un massatge suau.", benefits: ["Hidratació lleugera", "Absorció ràpida", "Pell suau i flexible"], size: "250 ml", suitableFor: "Tot tipus de pell" },
  "Pasta Blanquejadora": { ingredients: "Enzims de papaia, xilitol, hidroxiapatita i menta suau.", usage: "Raspallar durant dos minuts, al matí i a la nit. No esbandir en excés per prolongar l'efecte.", benefits: ["Blanqueja amb suavitat", "Protegeix l'esmalt", "Alè fresc"], size: "75 ml", suitableFor: "Ús diari, fins i tot en dents sensibles" },
  "Col·lutori de Sàlvia": { ingredients: "Olis essencials de sàlvia i menta, xilitol i extractes botànics.", usage: "Esbandir amb 15 ml durant 30 segons després del raspallat. No empassar ni diluir.", benefits: ["Alè duradorament fresc", "Cuida les genives", "Sense alcohol agressiu"], size: "236 ml", suitableFor: "Ús diari" },
  "Raspall de Bambú": { ingredients: "Mànec de bambú biodegradable i filaments suaus d'origen vegetal.", usage: "Utilitzar amb la pasta habitual i renovar cada tres mesos. Assecar a l'aire després de cada ús.", benefits: ["Neteja suau", "Zero plàstic", "Apte per a genives sensibles"], size: "1 unitat", suitableFor: "Tota la família" },
  "Tires Blanquejadores": { ingredients: "PAP+, hidroxiapatita i extracte de coco, sense peròxid agressiu.", usage: "Aplicar una tira sobre les dents seques durant 30 minuts, un cop al dia durant 14 dies.", benefits: ["Fins a 4 tons més blanques", "Sense sensibilitat", "Resultats en 14 dies"], size: "14 tires", suitableFor: "Adults que busquen un blanqueig a casa" },
  "Fil Dental de Menta": { ingredients: "Seda natural, cera de candel·lil·la i oli essencial de menta.", usage: "Tallar uns 40 cm i lliscar suaument entre les dents un cop al dia, preferiblement a la nit.", benefits: ["Neteja interdental", "Frescor de menta", "Biodegradable"], size: "30 m", suitableFor: "Ús diari, tot tipus d'espais interdentals" },
  "Sèrum de Genives": { ingredients: "Extracte de neem, àcid hialurònic, calèndula i vitamina E.", usage: "Aplicar unes gotes amb el dit o un raspall suau sobre la línia de les genives, a la nit i després del raspallat.", benefits: ["Enforteix les genives", "Calma la sensibilitat", "Hidrata la mucosa"], size: "50 ml", suitableFor: "Genives sensibles o amb tendència a sagnar" },
  "Pols de Carbó": { ingredients: "Carbó actiu de coco, bentonita i menta en pols.", usage: "Humiteja el raspall, agafa una mica de pols i raspalla suaument dues vegades per setmana.", benefits: ["Elimina taques superficials", "Neteja profunda", "Refresca l'alè"], size: "40 g", suitableFor: "Ús setmanal com a complement del raspallat" },
};

export function getProductDetails(name: string): ProductDetails {
  return details[name] ?? {
    ingredients: "Fórmula botànica seleccionada per a la cura diària.",
    usage: "Aplicar sobre la zona neta segons les necessitats de la pell.",
    benefits: ["Cura diària", "Textura agradable", "Fórmula mediterrània"],
    size: "Consulteu l'envàs",
    suitableFor: "Tot tipus de pell",
  };
}
