export interface ProductDetails {
  ingredients: string;
  usage: string;
  benefits: string[];
  size: string;
  suitableFor: string;
}

const details: Record<string, ProductDetails> = {
  "Óleo de Higo Chumbo": { ingredients: "Aceite de semilla de higo chumbo, escualano vegetal, vitamina E y extracto de romero.", usage: "Aplicar 3 o 4 gotas por la noche sobre rostro y cuello limpios. Masajear hasta su absorción.", benefits: ["Nutre intensamente", "Refuerza la barrera cutánea", "Suaviza líneas de expresión"], size: "30 ml", suitableFor: "Todo tipo de piel, especialmente seca o madura" },
  "Crema Alga Roja": { ingredients: "Extracto de alga roja, ácido hialurónico, agua marina y manteca de karité.", usage: "Aplicar mañana y noche después del sérum, con movimientos ascendentes.", benefits: ["Hidratación prolongada", "Calma la sensibilidad", "Mejora la elasticidad"], size: "50 ml", suitableFor: "Piel sensible, normal o deshidratada" },
  "Tónico Neroli": { ingredients: "Hidrolato de azahar, aloe vera, niacinamida y extracto de pepino.", usage: "Vaporizar sobre el rostro limpio o aplicar con un disco de algodón. No aclarar.", benefits: ["Refresca y equilibra", "Prepara la piel", "Aporta luminosidad"], size: "100 ml", suitableFor: "Todo tipo de piel" },
  "Limpiador de Arcilla": { ingredients: "Arcilla blanca, arcilla volcánica, glicerina vegetal y aceite de oliva.", usage: "Masajear sobre la piel húmeda durante un minuto y retirar con agua tibia.", benefits: ["Limpia en profundidad", "Purifica los poros", "Respeta la hidratación"], size: "120 ml", suitableFor: "Piel mixta, grasa o congestionada" },
  "Sérum Luminosidad": { ingredients: "Vitamina C estabilizada, extracto de granada, ácido ferúlico y aloe vera.", usage: "Aplicar 2 o 3 gotas por la mañana antes de la crema y del protector solar.", benefits: ["Unifica el tono", "Aporta luminosidad", "Protección antioxidante"], size: "30 ml", suitableFor: "Piel apagada o con tono irregular" },
  "Contorno de Ojos": { ingredients: "Péptidos de seda, cafeína, ácido hialurónico y extracto de aciano.", usage: "Aplicar una pequeña cantidad con suaves toques alrededor del contorno, mañana y noche.", benefits: ["Suaviza líneas", "Reduce bolsas", "Ilumina la mirada"], size: "15 ml", suitableFor: "Todo tipo de piel" },
  "Mascarilla de Noche": { ingredients: "Ceramidas, aceite de almendras, pantenol y extracto de lavanda.", usage: "Extender una capa fina antes de dormir, dos o tres noches por semana. Retirar por la mañana.", benefits: ["Repara durante la noche", "Nutre profundamente", "Recupera el confort"], size: "60 ml", suitableFor: "Piel seca, sensible o fatigada" },
  "Champú de Romero": { ingredients: "Extracto de romero, cafeína vegetal, aloe vera y tensioactivos suaves.", usage: "Aplicar sobre el cabello mojado, masajear el cuero cabelludo y aclarar. Repetir si es necesario.", benefits: ["Limpia suavemente", "Estimula el cuero cabelludo", "Aporta vitalidad"], size: "250 ml", suitableFor: "Cabello normal, fino o debilitado" },
  "Acondicionador de Karité": { ingredients: "Manteca de karité, aceite de jojoba, proteína de trigo y pantenol.", usage: "Aplicar de medios a puntas tras el champú. Dejar actuar de 2 a 3 minutos y aclarar.", benefits: ["Desenreda", "Nutre las puntas", "Reduce el encrespamiento"], size: "250 ml", suitableFor: "Cabello seco, rizado o dañado" },
  "Aceite de Argán": { ingredients: "Aceite de argán, escualano vegetal y vitamina E.", usage: "Distribuir 1 o 2 gotas en medios y puntas, sobre cabello húmedo o seco.", benefits: ["Aporta brillo", "Sella las puntas", "Suaviza sin apelmazar"], size: "50 ml", suitableFor: "Todo tipo de cabello" },
  "Bruma Capilar": { ingredients: "Agua de azahar, extracto de higo, pantenol y proteína vegetal.", usage: "Vaporizar a 20 cm sobre el cabello seco o húmedo. No necesita aclarado.", benefits: ["Perfuma delicadamente", "Refresca el cabello", "Aporta suavidad"], size: "100 ml", suitableFor: "Todo tipo de cabello" },
  "Mascarilla de Barro": { ingredients: "Arcilla rhassoul, minerales marinos, aceite de oliva y salvia.", usage: "Aplicar sobre cuero cabelludo y raíces húmedas. Dejar 10 minutos y aclarar abundantemente.", benefits: ["Elimina residuos", "Equilibra la raíz", "Devuelve ligereza"], size: "200 ml", suitableFor: "Cuero cabelludo graso o con acumulación" },
  "Sérum Anticaída": { ingredients: "Cafeína verde, péptidos vegetales, romero y niacinamida.", usage: "Aplicar por secciones sobre el cuero cabelludo limpio y masajear. No aclarar. Uso diario.", benefits: ["Fortalece la raíz", "Estimula el crecimiento", "Mejora la densidad"], size: "50 ml", suitableFor: "Cabello fino o con caída estacional" },
  "Exfoliante Sal Marina": { ingredients: "Sal marina fina, aceite de jojoba, menta y extracto de limón.", usage: "Masajear suavemente sobre el cuero cabelludo húmedo antes del champú, una vez por semana.", benefits: ["Desincrusta impurezas", "Activa la microcirculación", "Purifica la raíz"], size: "150 ml", suitableFor: "Todo tipo de cuero cabelludo, excepto irritado" },
  "Bálsamo Relajante": { ingredients: "Caléndula, lavanda, manteca de karité y bisabolol.", usage: "Aplicar sobre las zonas sensibilizadas y masajear hasta su absorción. Repetir cuando sea necesario.", benefits: ["Calma la irritación", "Nutre y protege", "Reduce la tirantez"], size: "75 ml", suitableFor: "Piel sensible, seca o irritada" },
  "Elixir de Sol": { ingredients: "Aceite de almendras, mica mineral dorada, vitamina E y extracto de zanahoria.", usage: "Agitar y aplicar sobre hombros, brazos y piernas. Evitar el contacto con tejidos claros.", benefits: ["Realza el bronceado", "Aporta brillo satinado", "Nutre la piel"], size: "100 ml", suitableFor: "Todo tipo de piel" },
  "Crema de Manos": { ingredients: "Manteca de limón, aceite de almendras, glicerina y vitamina E.", usage: "Masajear manos y cutículas tantas veces como sea necesario.", benefits: ["Repara la sequedad", "Suaviza cutículas", "Protege sin sensación grasa"], size: "50 ml", suitableFor: "Manos secas o expuestas" },
  "Spray Mineral": { ingredients: "Agua termal, magnesio, zinc y extracto de pepino.", usage: "Pulverizar sobre rostro o cuerpo y dejar absorber. Puede usarse durante todo el día.", benefits: ["Refresca al instante", "Calma el enrojecimiento", "Repone minerales"], size: "100 ml", suitableFor: "Todo tipo de piel, incluso sensible" },
  "Gel de Aloe Puro": { ingredients: "Aloe vera ecológico, pantenol, pepino y alantoína.", usage: "Aplicar generosamente sobre la piel limpia después del sol o cuando necesite calma.", benefits: ["Calma inmediatamente", "Hidrata sin grasa", "Ayuda a reparar"], size: "150 ml", suitableFor: "Piel sensible o expuesta al sol" },
  "Protector Urbano": { ingredients: "Filtros solares de amplio espectro, niacinamida, vitamina E y té verde.", usage: "Aplicar como último paso cada mañana. Renovar cada dos horas durante la exposición.", benefits: ["Protección SPF 50", "Defensa antioxidante", "Acabado invisible"], size: "50 ml", suitableFor: "Todo tipo de piel" },
  "Concentrado Reafirmante": { ingredients: "Péptidos tensores, ácido hialurónico, silicio orgánico y centella asiática.", usage: "Aplicar media ampolla sobre rostro, cuello y escote antes de la crema.", benefits: ["Efecto tensor", "Mejora la firmeza", "Hidratación concentrada"], size: "7 × 2 ml", suitableFor: "Piel madura o con pérdida de firmeza" },
  "Manteca Mediterránea": { ingredients: "Manteca de karité, aceite de oliva, jazmín y vitamina E.", usage: "Masajear sobre la piel limpia, insistiendo en las zonas más secas.", benefits: ["Nutrición intensa", "Suavidad duradera", "Perfume delicado"], size: "200 ml", suitableFor: "Piel normal a muy seca" },
  "Exfoliante de Oliva": { ingredients: "Hueso de aceituna micronizado, aceite de oliva, miel y romero.", usage: "Masajear sobre la piel húmeda con movimientos circulares y aclarar. Usar una o dos veces por semana.", benefits: ["Alisa la textura", "Retira células muertas", "Prepara para la hidratación"], size: "200 ml", suitableFor: "Todo tipo de piel corporal" },
  "Aceite Reafirmante": { ingredients: "Aceite de pepita de uva, hiedra, ciprés y centella asiática.", usage: "Masajear diariamente con movimientos ascendentes en piernas, abdomen y brazos.", benefits: ["Mejora la elasticidad", "Favorece el masaje drenante", "Nutre la piel"], size: "100 ml", suitableFor: "Piel con falta de firmeza" },
  "Gel de Baño Botánico": { ingredients: "Aloe vera, agua de azahar, glicerina vegetal y tensioactivos suaves.", usage: "Aplicar sobre la piel húmeda, masajear hasta formar espuma y aclarar.", benefits: ["Limpieza respetuosa", "Mantiene el confort", "Aroma botánico"], size: "300 ml", suitableFor: "Todo tipo de piel, incluso sensible" },
  "Crema de Cuello": { ingredients: "Péptidos, elastina vegetal, ácido hialurónico y aceite de rosa mosqueta.", usage: "Aplicar mañana y noche desde el escote hacia la mandíbula con movimientos ascendentes.", benefits: ["Mejora la firmeza", "Suaviza arrugas", "Hidrata cuello y escote"], size: "50 ml", suitableFor: "Piel madura o con pérdida de elasticidad" },
  "Desodorante de Piedra": { ingredients: "Alumbre potásico, agua de salvia, aloe vera y glicerina.", usage: "Humedecer ligeramente y deslizar sobre la piel limpia. Aclarar la piedra después de usar.", benefits: ["Control natural del olor", "Sin perfume intenso", "No deja residuos"], size: "90 g", suitableFor: "Todo tipo de piel" },
  "Leche Corporal": { ingredients: "Agua de rosas, aceite de almendras, aloe vera y vitamina E.", usage: "Aplicar diariamente sobre todo el cuerpo con un masaje suave.", benefits: ["Hidratación ligera", "Absorción rápida", "Piel suave y flexible"], size: "250 ml", suitableFor: "Todo tipo de piel" },
};

export function getProductDetails(name: string): ProductDetails {
  return details[name] ?? {
    ingredients: "Fórmula botánica seleccionada para el cuidado diario.",
    usage: "Aplicar sobre la zona limpia siguiendo las necesidades de la piel.",
    benefits: ["Cuidado diario", "Textura agradable", "Fórmula mediterránea"],
    size: "Consultar envase",
    suitableFor: "Todo tipo de piel",
  };
}